import type { Metadata } from "next";

import "./globals.css";
import { DM_Sans, Noto_Serif } from "next/font/google";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";

const notoSerifHeading = Noto_Serif({subsets:['latin'],variable:'--font-heading'});

const dmSans = DM_Sans({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", dmSans.variable, notoSerifHeading.variable)}
    >
      <body className="min-h-full flex flex-col">

        {/* {Navbar} */}

        <Toaster position="top-right" richColors />

        {children}





        {/* {footer } */}
      </body>
    </html>
  );
}
